### PR TITLE
Remove space from file name

### PR DESCRIPTION
**Pull request by jiriproX**
It causing failure when you run build second time

### CODE REVIEW

**Comment by jiriproX** [comment]
Running gofmt...
Running golangci-lint...
make: *** No rule to make target '.gopath/pkg/mod/github.com/blizzy78/varnamelen@v0.8.0/testdata/src/falsenegativechanrecv/chanrecv', needed by '/opt/cek/sriov-cni/build/sriov'.  Stop.

**Comment by blizzy78** [comment]
Thanks, good catch! 👀

**Comment by jiriproX** [comment]
Can you please create/tag new minor version v0.8.1 with this fix?

**Comment by jiriproX** [comment]
@blizzy78  Can you please create/tag new minor version v0.8.1 with this fix? I need to push that change to another third party project which suffers with this issue as well.

**Comment by jiriproX** [comment]
@blizzy78 Can you please create/tag new minor version v0.8.1 with this fix? I need to push that change to another third party project which suffers with this issue as well. When new version will be available?

**Comment by jiriproX** [comment]
Can you please create new version 0.8.1 which includes that change? We are waiting for it.

**Pull request merged**
